# Generated by Django 4.2.3 on 2023-08-02 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20, unique=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=50, unique=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.categories')),
            ],
            options={
                'db_table': 'merchant_xref',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('pymt_method', models.CharField(blank=True, max_length=2)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.categories')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.merchant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.CharField(max_length=40)),
                ('income_dt', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'income',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('housing_lmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utility_lmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transportation_lmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grocery_lmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('healthcare_lmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dining_lmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entertainment_lmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clothing_lmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('miscellaneous_lmt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.CharField(blank=True, max_length=1, null=True)),
                ('eff_from', models.DateTimeField(blank=True, null=True)),
                ('eff_to', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget',
                'managed': True,
            },
        ),
    ]
